### ISSUE TITLE
Problem with Sampctl

### ISSUE THREAD

**Issue by sanpezlo** [kristoisberg/samp-td-streamer#4]
I had a problem with the installation of the package via Sampctl

ERROR: Get https://github.com/kristoisberg/samp-td-streamer/info/refs?service=git-upload-pack: net/http: TLS handshake timeout

When I saw this, I decided to uninstall and reinstall it, and now this comes out:

WARN: failed to ensure package github.com/kristoisberg/samp-td-streamer: failed to ensure dependency from cache: remote repository is empty

**Comment by Southclaws** [comment]
Delete your local cache in ~/.samp/packages
